import {EventEmitter, Injectable} from '@angular/core';
import {ApplianceModel} from '../../home/appliance-grid/appliance.model';
import {HvacGridModel} from '../../home/hvac-grid/hvac-grid-model';
import {LightingModel} from '../../home/lighting-grid/lighting.model';
import {SafetyStatusModel} from '../../home/safety-status/safety-status-model';
import {DeviceStatsModel} from '../../home/device-stats/device-stats.model';
import {ParkingStatusModel} from '../../home/parking-status/parking-status-model';
import {OrganizationModel} from '../../home/organization-stats/organization.model';
import {VisitorModel} from '../../home/visitor-stats/visitor.model';
import {SkSliderModel} from '../../home/sk-slider-model';

@Injectable()
export class DataPassService {
    public menuIsActive = false;
    public loaderStack = [];
    public currentLang = 'fa';
    public userPermissions = [];
    public roleName = '';
    public searchTriggered = new EventEmitter<boolean>();
    public subsidiaryChanged = new EventEmitter<any>();
    public homeSelected = new EventEmitter<boolean>();
    public footerClicked = new EventEmitter<boolean>();
    public searchMode = false;
    public searchText = '';
    public selectedVisitor: any;
    public filterIsActive = false;
    public selectedfilterType = '';
    public footerActiveIcon = 'home';
    public isBackActive = false;
    public manageMode = false;
    public isLoggedIn = false;
    public loggedInUser: any;
    public organizationId: any;
    public selectedSubsidiary: any = null;
    public selectedDevice: any;
    public selectedPoint: any;
    public selectedUser: any;
    public selectedCardHolder: any;
    public selectedHvac: any;
    public sosStatus = 0;
    public panicStatus = false;
    public selectedCamera = 'cam1';
    public camera1: any = null;
    public camera2: any = null;
    public notificationsStack = [];
    public notificationsCount = 0;
    public selectedAlert: any;
    public nodeCount = 0;
    public selectedScenario: any;
    public hvacModel: HvacGridModel = new HvacGridModel({});
    public applianceModel: ApplianceModel = new ApplianceModel({});
    public lightingModel: LightingModel = new LightingModel({});
    public safetyDeviceModel: SafetyStatusModel = new SafetyStatusModel({});
    public deviceStatsModel: DeviceStatsModel = new DeviceStatsModel({});
    public parkingModel: ParkingStatusModel = new ParkingStatusModel({});
    public organizationModel: OrganizationModel = new OrganizationModel({});
    public visitorModel: VisitorModel = new VisitorModel({});
    public signageModel:SkSliderModel=new SkSliderModel({});
    public visitorCount = 0;
    public organization: any;
    public subsidiaryList = [];
    public campusList = [];
    public buildingList = [];
    public floorList = [];
    public areaList = [];
    public nodeList = [];
    public timeStamp = new Date();
    public leadIcon='';

    clearLocalData() {
        this.menuIsActive = false;
        this.loaderStack = [];
        this.currentLang = 'fa';
        this.userPermissions = [];
        this.roleName = '';
        this.searchTriggered = new EventEmitter<boolean>();
        this.subsidiaryChanged = new EventEmitter<any>();
        this.homeSelected = new EventEmitter<boolean>();
        this.footerClicked = new EventEmitter<boolean>();
        this.searchMode = false;
        this.searchText = '';
        this.selectedVisitor = null;
        this.filterIsActive = false;
        this.selectedfilterType = '';
        this.footerActiveIcon = 'home';
        this.isBackActive = false;
        this.manageMode = false;
        this.isLoggedIn = false;
        this.loggedInUser = null;
        this.organizationId = null;
        this.selectedSubsidiary = null;
        this.selectedDevice = null;
        this.selectedPoint = null;
        this.selectedUser = null;
        this.selectedCardHolder = null;
        this.selectedHvac = null;
        this.sosStatus = 0;
        this.panicStatus = false;
        this.selectedCamera = 'cam1';
        this.camera1 = null;
        this.camera2 = null;
        this.notificationsStack = [];
        this.notificationsCount = 0;
        this.selectedAlert = null;
        this.nodeCount = 0;
        this.selectedScenario = null;
        this.hvacModel = new HvacGridModel({});
        this.applianceModel = new ApplianceModel({});
        this.lightingModel = new LightingModel({});
        this.safetyDeviceModel = new SafetyStatusModel({});
        this.deviceStatsModel = new DeviceStatsModel({});
        this.parkingModel = new ParkingStatusModel({});
        this.organizationModel = new OrganizationModel({});
        this.visitorModel = new VisitorModel({});
        this.signageModel = new SkSliderModel({});
        this.visitorCount = 0;
        this.organization = null;
        this.subsidiaryList = [];
        this.campusList = [];
        this.buildingList = [];
        this.floorList = [];
        this.areaList = [];
        this.nodeList = [];
        this.timeStamp = new Date();
    }
}
